# Assignment-02


### Numpy Array Operations

Write a short introduction about Numpy and list the chosen functions. 

- count_nonzero()
- append()
- insert()
- isnan()
- random.rand()

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --quiet
import numpy as np
import jovian

<IPython.core.display.Javascript object>

## Function 1 : 
count_nonzero() : It returns the number of non Zero elements in an multidimensional array.


In [2]:
arr = [[0, 1, 2, 0, 4], [5, 0, 6, 0, 7]]
np.count_nonzero(arr)

6

In [3]:
arr = np.array([[[1,2,3],[0,0,7]],
        [[15,12,0],[90,0,1]]])
np.count_nonzero(arr)

8

In [4]:
arr = np.array([[[1,2,3,0,2],[7,8,0,9,7]],
        [[15,12,0,0,0],[90,0,0,0,0]]])
np.count_nonzero(arr)

11

## Function 2 :
append(): It adds the passed object in a given list

In [5]:
my_list = [1,2,3,4,5,6]
my_list.append(7)
my_list

[1, 2, 3, 4, 5, 6, 7]

In [6]:
my_list = []
my_list.append(1000)
my_list

[1000]

In [7]:
my_list = [1,2,3] 
my_list.append(2.15)
my_list

[1, 2, 3, 2.15]

## Function 3 :
insert(): This adds an element at a given index in a list 

In [8]:
my_list

[1, 2, 3, 2.15]

In [9]:
my_list.insert(3,8)
my_list

[1, 2, 3, 8, 2.15]

In [10]:
my_list.insert(0,0)
my_list

[0, 1, 2, 3, 8, 2.15]

## Function 4:
isnan() : It tests element-wise whether it is NaN or not and returns the result as a boolean array.

In [11]:
np.isnan(1)

False

In [12]:
np.isnan(np.nan)

True

In [13]:
np.isnan(True)

False

## Function 5:
random.rand() : It is used to generate random numbers or values in a given shape.

In [14]:
np.random.rand(6,3)

array([[0.81303946, 0.8962516 , 0.34291268],
       [0.78807982, 0.16733007, 0.10889876],
       [0.89693795, 0.64008785, 0.80675515],
       [0.52027733, 0.25450571, 0.2306142 ],
       [0.04771521, 0.88757905, 0.86967952],
       [0.44064603, 0.97665149, 0.61842945]])

In [15]:
np.random.rand(7,5)

array([[0.13368972, 0.83021271, 0.49846935, 0.18122921, 0.3910002 ],
       [0.91747541, 0.36766315, 0.79264951, 0.55224582, 0.8332612 ],
       [0.70128564, 0.93699635, 0.67785955, 0.21561761, 0.38574232],
       [0.10243263, 0.733998  , 0.78872856, 0.64348943, 0.68058029],
       [0.79636464, 0.20255449, 0.59822965, 0.80217424, 0.94209021],
       [0.01479866, 0.23058005, 0.58235367, 0.18722359, 0.91363024],
       [0.87193444, 0.71763868, 0.26684616, 0.03950304, 0.04878723]])

In [16]:
np.random.rand(1,2)

array([[0.193829  , 0.32179543]])

In [17]:
jovian.commit(project='numPy-Assignment-02', evironment=None)

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Creating a new project "cpahuja0123/numPy-Assignment-02"
[jovian] Committed successfully! https://jovian.ai/cpahuja0123/numpy-assignment-02


'https://jovian.ai/cpahuja0123/numpy-assignment-02'